# Animations: Durations (in milliseconds)
DEFAULT_VISIBILITY_TOGGLE_DURATION_MS = 200
DEFAULT_DIALOG_ANIM_DURATION_MS = 300
DEFAULT_SHAKE_DURATION_MS = 200
DEFAULT_FLASH_DURATION_MS = 2000
DEFAULT_TABLE_ROW_FLASH_DURATION_MS = 1200
WAVE_SPINNER_ANIM_DURATION_MS = 400
WAVE_SPINNER_DELAY_STEP_MS = 120

# Animations: Values \ Properties
DEFAULT_SHAKE_AMOUNT = 4

# UI Colors
FLASH_SUCCESS_COLOR = "#50fa7b"
FLASH_DANGER_COLOR = "#ff5555"
DEFAULT_TABLE_ROW_HIGHLIGHT_COLOR = "#2ca878"
TABLE_SELECTION_COLOR_HEX = "#44689e"
WAVE_SPINNER_DEFAULT_COLOR = "#8be9fd"
LOADING_OVERLAY_BG_COLOR = "rgba(20, 20, 20, 180)"

# UI: Wave Spinner
WAVE_SPINNER_DOT_COUNT = 5
WAVE_SPINNER_SPACING = 10
WAVE_SPINNER_MIN_DOT_SIZE = 20
WAVE_SPINNER_MAX_DOT_SIZE = 35

# UI: Loading Overlay
LOADING_OVERLAY_BORDER_RADIUS = "10px"
LOADING_OVERLAY_SPACING = 20
LOADING_OVERLAY_FONT_SIZE_PX = 16


